version: '3'
services:

  database: # Container for MYSQL db
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword

  db_admin: # Container for managing DB access
    image: adminer
    restart: always
    ports:
      - 8000:8080

  app: # Container for frotnend React APP
    build: ./frontend
    ports:
      - "3000:80"
